"use client";
import Image from "next/image";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";
import { RefObject, useEffect, useRef, useState } from "react";
import { VVCLogo } from "./VVCLogo";
import { ContactForm } from "./ContactForm";

const stages=["A GENTE CONVERSA","EU MONTO O MODELO","VOCÊ ABRE E OLHA","A GENTE FALA DE VALOR","SEU SITE ENTRA NO AR"];
const services=[
  ["Site institucional","Tudo que o seu cliente procura: serviço, preço, horário, endereço e contato.","01"],
  ["Cardápio no WhatsApp","O cliente monta o pedido e ele chega direto no seu número, sem intermediário.","02"],
  ["Agendamento online","Serviço, dia e horário escolhidos pelo cliente, a qualquer hora.","03"],
  ["Catálogo de produtos","Foto, tamanho, cor, preço e filtros, com pedido direto no WhatsApp.","04"],
  ["Landing page","Uma página com um único objetivo: orçamento, promoção ou captação.","05"],
  ["Formulário sob medida","As perguntas certas para o orçamento chegar organizado.","06"],
  ["Presença no Google","Estrutura preparada para a busca local encontrar o seu negócio.","07"]
];

function MagneticButton({href,children}:{href:string;children:React.ReactNode}){const x=useMotionValue(0),y=useMotionValue(0);return <motion.a href={href} className="button" style={{x,y}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.12);y.set((e.clientY-r.top-r.height/2)*.12)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.a>}

function useSectionProgress(ref:RefObject<HTMLElement|null>, mode:"pinned"|"passing"="pinned"){
  const progress=useMotionValue(0);
  useEffect(()=>{let frame=0;const update=()=>{frame=0;const el=ref.current;if(!el)return;const rect=el.getBoundingClientRect();const total=mode==="pinned"?Math.max(1,el.offsetHeight-window.innerHeight):el.offsetHeight+window.innerHeight;const passed=mode==="pinned"?-rect.top:window.innerHeight-rect.top;progress.set(Math.max(0,Math.min(1,passed/total)));};const request=()=>{if(!frame)frame=requestAnimationFrame(update)};update();window.addEventListener("scroll",request,{passive:true});window.addEventListener("resize",request);return()=>{window.removeEventListener("scroll",request);window.removeEventListener("resize",request);if(frame)cancelAnimationFrame(frame)}} ,[ref,mode,progress]);
  return progress;
}

export function VVCExperience(){
  const intro=useRef<HTMLElement>(null), horizontal=useRef<HTMLElement>(null), sculpture=useRef<HTMLElement>(null);
  const introP=useSectionProgress(intro); const logoP=useTransform(introP,[0,.48],[0,1]); const heroOpacity=useTransform(introP,[.5,.74],[0,1]); const heroY=useTransform(introP,[.5,.85],[80,0]); const logoScale=useTransform(introP,[.48,.75],[1,.22]); const logoY=useTransform(introP,[.48,.75],[0,-300]);
  const horP=useSectionProgress(horizontal); const hx=useTransform(horP,[0,1],["0%","-80%"]);
  const scP=useSectionProgress(sculpture,"passing"); const rotate=useTransform(scP,[0,1],[-18,18]); const [pointer,setPointer]=useState({x:0,y:0});
  return <main>
    <section ref={intro} className="intro" id="top"><div className="intro-sticky">
      <motion.div className="intro-mark" style={{scale:logoScale,y:logoY}}><VVCLogo progress={logoP}/><motion.span style={{opacity:logoP}}>DIGITAL STUDIO</motion.span></motion.div>
      <motion.div className="hero" style={{opacity:heroOpacity,y:heroY}}><nav><a href="#top" aria-label="Viveci, início"><b>VVC</b><span>VIVECI / DIGITAL STUDIO</span></a><div><a href="#servicos">SERVIÇOS</a><a href="#processo">COMO FUNCIONA</a><a href="#sobre">SOBRE</a><a href="#duvidas">DÚVIDAS</a><a className="nav-cta" href="#contato">QUERO VER MEU MODELO</a></div></nav><div className="hero-copy"><p className="eyebrow">VIVECI / SITES PARA EMPRESAS LOCAIS</p><h1>O SEU SITE PRONTO<br/>ANTES DE VOCÊ <i>PAGAR.</i></h1><p className="hero-sub">Eu monto o site do seu negócio, te mostro funcionando e só depois a gente conversa sobre valor. Sem custo para ver, sem compromisso para recusar.</p><MagneticButton href="#contato">QUERO VER MEU MODELO <span>↗</span></MagneticButton><a className="hero-secondary" href="#processo">VER COMO FUNCIONA ↓</a></div><div className="hero-image"><Image src="/images/vvc-architecture.png" alt="Arquitetura italiana contemporânea em travertino, ao anoitecer" fill priority sizes="(max-width: 800px) 100vw, 55vw"/><div className="interface-frame"><span>VVC / VIVECI</span><span>VER ANTES. DECIDIR DEPOIS.</span></div></div><div className="hero-index">MODELO SEM CUSTO · VOCÊ SÓ PAGA SE APROVAR <span>SCROLL PARA EXPLORAR ↓</span></div></motion.div>
      <motion.div className="scroll-cue" style={{opacity:useTransform(introP,[0,.08,.2],[1,1,0])}}>SCROLL PARA CONSTRUIR <span>↓</span></motion.div>
    </div></section>
    <section className="statement section-pad" id="problema"><div className="section-label">O PROBLEMA <span>01</span></div><div className="statement-grid"><p>Cliente fiel você já tem.<br/>A questão é quem ainda<br/>não conhece o seu negócio.</p><h2>SEU NEGÓCIO FUNCIONA.<br/>O PROBLEMA É QUEM<br/><em>AINDA NÃO TE CONHECE.</em></h2></div><div className="pain-grid">{[["Você não aparece","Quem pesquisa o seu serviço no Google já decidiu comprar. Nessa hora, aparece quem tem site."],["A venda depende de resposta","Direct e WhatsApp só funcionam quando alguém está olhando. O cliente decide às onze da noite."],["O canal não é seu","Instagram é alcance emprestado. Aplicativo leva comissão. Um site é um endereço próprio."],["A pergunta se repete","Preço, horário e serviço poderiam estar respondidos antes mesmo da primeira mensagem."]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
    <section ref={horizontal} className="horizontal" id="processo"><div className="horizontal-sticky"><div className="horizontal-head"><span>COMO FUNCIONA</span><span>CINCO PASSOS · VOCÊ SÓ PAGA NO QUARTO</span></div><motion.div className="track" style={{x:hx}}>{stages.map((s,i)=><article key={s}><span>0{i+1}</span><h3>{s}</h3><p>{["Você me diz que negócio é, o que precisa e o que hoje dá mais trabalho. Cinco minutos por WhatsApp resolvem.","Com seu nome, cores, serviços e informações. Se tiver logo e fotos, me manda; se não, começo pelo que já existe.","Recebe o link, navega no celular e mostra para quem quiser. Sem custo e sem compromisso.","Você diz o que quer mudar e o que falta. Com o escopo definido, eu passo o valor fechado, sem surpresa.","Faço os ajustes finais, publico no seu endereço e deixo tudo preparado para aparecer no Google."][i]}</p><div className="panel-glyph" aria-hidden>{i%2===0?"╲╱":"┌─┐"}</div></article>)}</motion.div><div className="progress"><motion.i style={{scaleX:horP}}/></div></div></section>
    <section className="model-offer section-pad"><div className="section-label">A OFERTA <span>02</span></div><div className="model-grid"><h2>EU MONTO PRIMEIRO.<br/><em>VOCÊ DECIDE DEPOIS.</em></h2><div><p className="model-lead">Nenhum negócio deveria pagar por um site que ainda não viu.</p><p>Eu inverto a ordem: monto o modelo com o seu nome e as suas informações e mando pronto para você abrir. Você não paga nada para ver, não assina nada e não precisa responder na hora.</p><p>Se não for para agora, eu paro por aí. Se você enxergar o seu negócio ali dentro, então conversamos sobre o que falta e quanto custa.</p><MagneticButton href="#contato">QUERO VER O MEU MODELO ↗</MagneticButton></div></div></section>
    <section className="services section-pad" id="servicos"><div className="section-label">O QUE EU FAÇO <span>03</span></div><div className="services-title"><h2>SEU CLIENTE ENCONTRA<br/>ANTES DE <em>PERGUNTAR.</em></h2><p>Sites que resolvem a dúvida antes de alguém precisar responder uma mensagem.</p></div><div className="service-list">{services.map(([n,d,i])=><article key={n}><span>{i}</span><h3>{n}</h3><p>{d}</p><b>↗</b><div className="service-preview" aria-hidden><VVCLogo/></div></article>)}</div><div className="scope-note"><b>O QUE NÃO ESTÁ INCLUSO</b><p>Não produzo fotos profissionais, não redesenho logo, não escrevo blog contínuo e não faço gestão de redes sociais ou anúncios. Se faltar material, eu digo exatamente o que precisa ser produzido.</p></div></section>
    <section className="technology section-pad"><div className="section-label light">O QUE VEM DENTRO <span>04</span></div><h2>A TÉCNICA EXISTE PARA<br/>O SEU CLIENTE <em>NÃO<br/>DESISTIR</em> NO CAMINHO.</h2><div className="tech-grid">{[["CELULAR PRIMEIRO","Construído e testado na tela que o seu cliente realmente usa."],["RÁPIDO DE ABRIR","Imagem no tamanho certo, código enxuto, nada carregando sem necessidade."],["PREPARADO PARA O GOOGLE","Título, descrição, endereço e informações estruturadas para a busca."],["NAVEGAÇÃO SEM DÚVIDA","A ação principal está sempre no lugar certo, inclusive no celular."],["MOVIMENTO COM PROPÓSITO","Animação guia o olho sem atrasar a leitura ou virar enfeite."],["LEGÍVEL PARA TODOS","Contraste, toque e estrutura preparados para diferentes formas de navegar."],["FEITO PARA CONVERTER","Cada seção responde uma dúvida que poderia travar a decisão."]].map(([t,d],i)=><div key={t}><span>0{i+1}</span><b>{t}</b><p>{d}</p><i/></div>)}</div></section>
    <section className="benefits section-pad"><div className="section-label">O QUE MUDA NO SEU DIA <span>05</span></div><h2>NÃO É SOBRE TER UM SITE.<br/>É SOBRE PARAR DE <em>PERDER CLIENTE</em><br/>PELOS MESMOS MOTIVOS.</h2><div>{[["Pedido direto","Sem comissão do aplicativo"],["Agenda 24 horas","Sem perder horário por demora na resposta"],["Preço público","Sem repetir a mesma informação todo dia"],["Presença no Google","Encontrado mesmo com a loja fechada"],["Avaliações visíveis","Confiança antes da primeira conversa"],["Canal próprio","Independente do alcance do Instagram"]].map(([a,b])=><article key={a}><b>{a}</b><span>→</span><p>{b}</p></article>)}</div></section>
    <section ref={sculpture} className="sculpture" onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();setPointer({x:(e.clientX-r.left-r.width/2)/30,y:(e.clientY-r.top-r.height/2)/30})}}><div className="sculpture-copy"><span>A ORIGEM DO NOME</span><h2>VENI. VIDI. <em>VICI.</em></h2><p>Viveci vem dos três verbos do símbolo VVC. Não é sobre conquista. É sobre a ordem: primeiro eu chego ao seu negócio, depois entendo como ele funciona e só então construo.</p></div><motion.div className="sculpture-mark" style={{rotateY:useSpring(pointer.x),rotateX:useSpring(-pointer.y),rotateZ:rotate}}><VVCLogo/></motion.div></section>
    <section className="philosophy section-pad"><div className="section-label">COMO EU TRABALHO <span>QUATRO REGRAS</span></div><div>{[["MOSTRAR ANTES DE PROMETER","O modelo vem primeiro; a conversa de valor, depois."],["SEM PROMESSA VAZIA","Eu entrego o negócio encontrável, claro e aberto 24 horas — sem inventar resultado."],["UMA COISA BEM FEITA","Uma página completa e rápida ganha de cinco páginas vazias."],["O SITE É SEU","O endereço e o conteúdo ficam no nome do seu negócio."]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
    <section className="about section-pad" id="sobre"><div className="about-photo"><Image src="/images/vvc-architecture.png" alt="Detalhe arquitetônico em pedra e vidro" fill sizes="50vw"/></div><div><div className="section-label light">QUEM FAZ <span>06</span></div><h2>UM ESTÚDIO PEQUENO.<br/><em>DE PROPÓSITO.</em></h2><p>Meu nome é Enzo. Eu crio sites para empresas locais — as que atendem cliente todo dia, no balcão, na cadeira, na oficina e no telefone.</p><p>A Viveci nasceu ao perceber negócios bons, com cliente fiel, que ainda eram difíceis de encontrar. Aqui não tem atendente nem gerente de contas: você fala comigo, e quem escreve o código é quem responde.</p><p>Não trabalho com pacote fechado porque cada empresa precisa de uma coisa diferente. E mostro o site antes de cobrar porque é mais fácil você olhar do que eu explicar.</p><a href="#contato" className="text-link">FALAR COMIGO ↗</a></div></section>
    <section className="investment section-pad"><div className="section-label">INVESTIMENTO <span>07</span></div><div><h2>QUANTO<br/><em>CUSTA?</em></h2><article><h3>Não tenho tabela. E tem um motivo.</h3><p>Um cardápio de pizzaria e um catálogo com trezentos produtos não dão o mesmo trabalho. Eu ajusto o valor ao porte do negócio e ao tamanho do site.</p><p>Primeiro eu monto o modelo. Você olha, diz o que falta e o que quer mudar. Com o escopo definido, eu passo o valor fechado — sem surpresa e sem cobrança por algo que não combinamos.</p><MagneticButton href="#contato">PEDIR MEU MODELO E DESCOBRIR O VALOR ↗</MagneticButton></article></div></section>
    <section className="faq section-pad" id="duvidas"><div className="section-label">DÚVIDAS <span>08</span></div><h2>ANTES DE<br/>VOCÊ <em>PERGUNTAR.</em></h2><div>{[["O modelo é grátis mesmo?","É. Você não paga nada para ver, não assina nada e não passa dado de cartão. Se não gostar, a conversa acaba ali."],["Eu já tenho Instagram. Preciso de site?","Instagram fala com quem já te conhece. O site também encontra quem procura seu serviço agora, no Google — e é um canal que é seu."],["Quanto custa?","Não trabalho com pacote fechado. O valor é definido depois que você vê o modelo e me diz o que precisa ter nele."],["Não tenho logo nem fotos boas. Dá para fazer?","Dá. Eu começo com o que já existe no Google e nas redes e explico o que vale produzir depois."],["Quem fica com o domínio?","O endereço fica registrado no nome do seu negócio. O site e o endereço são seus."],["Já tive site e não deu em nada.","Deixa eu montar o modelo sem custo para você comparar com o que teve. Você decide olhando, não pela promessa."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="contact section-pad" id="contato"><div className="contact-lead"><span>SEM CUSTO · SEM COMPROMISSO</span><h2>VAMOS VER<br/>COMO <em>FICA?</em></h2><p>Me diz qual é o seu negócio e eu começo pelo modelo. Você não precisa decidir nada agora. Só olhar.</p></div><ContactForm/></section>
    <footer><div className="footer-top"><div><b>VVC</b><span>VIVECI — SITES PARA NEGÓCIOS QUE ATENDEM GENTE TODO DIA.</span></div><div><a href="#servicos">SERVIÇOS</a><a href="#processo">COMO FUNCIONA</a><a href="#sobre">SOBRE</a><a href="#duvidas">DÚVIDAS</a></div><div><a href="#contato">QUERO VER MEU MODELO ↗</a><span>CONTATO DIRETO COM QUEM FAZ</span></div></div><div className="footer-mark" aria-hidden>V V C</div><div className="footer-bottom"><span>© 2026 VIVECI</span><span>VENI · VIDI · VICI</span><a href="#top">VOLTAR AO TOPO ↑</a></div></footer>
  </main>
}
